/**
 * CreateBindPolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { BindFairnessPolicyRequest } from "@guardloop/core/use-cases";
import { useCasesSchemas } from "@guardloop/core/use-cases";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "usc";

export function createCreateBindPolicyRequest(overrides: Partial<BindFairnessPolicyRequest> = {}) {
  const raw = {
    appetiteLimitId: overrides.appetiteLimitId ?? `apl_${ulid().toLowerCase()}`,
    fairnessPolicyId: overrides.fairnessPolicyId ?? `fpol_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return useCasesSchemas.BindFairnessPolicyRequest.parse(raw);
}
