/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@guardloop/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAssessmentsDomainModule,
  buildControlsDomainModule,
  buildExplanationsDomainModule,
  buildIdentityDomainModule,
  buildMonitoringDomainModule,
  buildPoliciesDomainModule,
  buildRemediationsDomainModule,
  buildReportingDomainModule,
  buildUseCasesDomainModule,
} from "../domains/index.js";
import type {
  AssessmentsDomainModule,
  ControlsDomainModule,
  ExplanationsDomainModule,
  IdentityDomainModule,
  MonitoringDomainModule,
  PoliciesDomainModule,
  RemediationsDomainModule,
  ReportingDomainModule,
  UseCasesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private assessmentsModule: AssessmentsDomainModule | null = null;
  private controlsModule: ControlsDomainModule | null = null;
  private explanationsModule: ExplanationsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private monitoringModule: MonitoringDomainModule | null = null;
  private policiesModule: PoliciesDomainModule | null = null;
  private remediationsModule: RemediationsDomainModule | null = null;
  private reportingModule: ReportingDomainModule | null = null;
  private useCasesModule: UseCasesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get assessments domain module
   */
  getAssessmentsDependencies(): AssessmentsDomainModule {
    if (!this.assessmentsModule) {
      this.assessmentsModule = buildAssessmentsDomainModule(this.dynamoClient);
    }
    return this.assessmentsModule;
  }

  /**
   * Get controls domain module
   */
  getControlsDependencies(): ControlsDomainModule {
    if (!this.controlsModule) {
      this.controlsModule = buildControlsDomainModule(this.dynamoClient);
    }
    return this.controlsModule;
  }

  /**
   * Get explanations domain module
   */
  getExplanationsDependencies(): ExplanationsDomainModule {
    if (!this.explanationsModule) {
      this.explanationsModule = buildExplanationsDomainModule(this.dynamoClient);
    }
    return this.explanationsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get monitoring domain module
   */
  getMonitoringDependencies(): MonitoringDomainModule {
    if (!this.monitoringModule) {
      this.monitoringModule = buildMonitoringDomainModule(this.dynamoClient);
    }
    return this.monitoringModule;
  }

  /**
   * Get policies domain module
   */
  getPoliciesDependencies(): PoliciesDomainModule {
    if (!this.policiesModule) {
      this.policiesModule = buildPoliciesDomainModule(this.dynamoClient);
    }
    return this.policiesModule;
  }

  /**
   * Get remediations domain module
   */
  getRemediationsDependencies(): RemediationsDomainModule {
    if (!this.remediationsModule) {
      this.remediationsModule = buildRemediationsDomainModule(this.dynamoClient);
    }
    return this.remediationsModule;
  }

  /**
   * Get reporting domain module
   */
  getReportingDependencies(): ReportingDomainModule {
    if (!this.reportingModule) {
      this.reportingModule = buildReportingDomainModule(this.dynamoClient);
    }
    return this.reportingModule;
  }

  /**
   * Get use-cases domain module
   */
  getUseCasesDependencies(): UseCasesDomainModule {
    if (!this.useCasesModule) {
      this.useCasesModule = buildUseCasesDomainModule(this.dynamoClient);
    }
    return this.useCasesModule;
  }

  clearAssessmentsDependencies(): void { this.assessmentsModule = null; }
  clearControlsDependencies(): void { this.controlsModule = null; }
  clearExplanationsDependencies(): void { this.explanationsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearMonitoringDependencies(): void { this.monitoringModule = null; }
  clearPoliciesDependencies(): void { this.policiesModule = null; }
  clearRemediationsDependencies(): void { this.remediationsModule = null; }
  clearReportingDependencies(): void { this.reportingModule = null; }
  clearUseCasesDependencies(): void { this.useCasesModule = null; }

  getAssessmentsDependenciesForRequest(): AssessmentsDomainModule {
    return this.getAssessmentsDependencies();
  }

  getControlsDependenciesForRequest(): ControlsDomainModule {
    return this.getControlsDependencies();
  }

  getExplanationsDependenciesForRequest(): ExplanationsDomainModule {
    return this.getExplanationsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getMonitoringDependenciesForRequest(): MonitoringDomainModule {
    return this.getMonitoringDependencies();
  }

  getPoliciesDependenciesForRequest(): PoliciesDomainModule {
    return this.getPoliciesDependencies();
  }

  getRemediationsDependenciesForRequest(): RemediationsDomainModule {
    return this.getRemediationsDependencies();
  }

  getReportingDependenciesForRequest(): ReportingDomainModule {
    return this.getReportingDependencies();
  }

  getUseCasesDependenciesForRequest(): UseCasesDomainModule {
    return this.getUseCasesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.assessmentsModule = null;
    this.controlsModule = null;
    this.explanationsModule = null;
    this.identityModule = null;
    this.monitoringModule = null;
    this.policiesModule = null;
    this.remediationsModule = null;
    this.reportingModule = null;
    this.useCasesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
