/**
 * CreateSandboxEvidence DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SandboxEvidenceCreateRequest } from "@guardloop/core/controls";
import { controlsSchemas } from "@guardloop/core/controls";

export function createCreateSandboxEvidenceRequest(overrides: Partial<SandboxEvidenceCreateRequest> = {}) {
  const raw = {
    comments: overrides.comments ?? [],
    lineOfDefence: overrides.lineOfDefence ?? "lod1",
    ...overrides,
  };

  return controlsSchemas.SandboxEvidenceCreateRequest.parse(raw);
}
