/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportingDomainModule } from "../dependencies/reporting-ddd.dependencies.js";
import type { AuditExportCreateRequest } from "@guardloop/core/reporting/types";
import type { CreateAuditExportInput, GetAuditExportInput, ListAuditExportsInput } from "@guardloop/services/reporting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reporting/exports
 * Operation: listAuditExports
 */
export async function listAuditExports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAuditExportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.exports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/reporting/exports
 * Operation: createAuditExport
 */
export async function createAuditExport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AuditExportCreateRequest }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAuditExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/reporting/exports/{reportId}
 * Operation: getAuditExport
 */
export async function getAuditExport(
  request: FastifyRequest<{ Params: { reportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAuditExportInput = {
    reportId: request.params.reportId,
  };
  const result = await deps.useCases.exports.get.execute(input);
  return reply.code(200).send(result);
}


