/**
 * GetAssessment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRiskAssessmentParams } from "@guardloop/core/assessments";

export function createGetAssessmentRequest(overrides: Partial<GetRiskAssessmentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
