/**
 * CreateUseCase DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AiUseCaseCreateRequest } from "@guardloop/core/use-cases";
import { useCasesSchemas } from "@guardloop/core/use-cases";

export function createCreateUseCaseRequest(overrides: Partial<AiUseCaseCreateRequest> = {}) {
  const raw = {
    customerImpacting: overrides.customerImpacting ?? faker.datatype.boolean(),
    name: overrides.name ?? faker.person.fullName(),
    ...overrides,
  };

  return useCasesSchemas.AiUseCaseCreateRequest.parse(raw);
}
