/**
 * GetUseCase DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAiUseCaseParams } from "@guardloop/core/use-cases";

export function createGetUseCaseRequest(overrides: Partial<GetAiUseCaseParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
