/**
 * ListUseCase DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAiUseCasesParams } from "@guardloop/core/use-cases";

export function createListUseCaseRequest(overrides: Partial<ListAiUseCasesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
