/**
 * Assessments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assessments Domain Module - Composition root
 *
 * DDD: Composition root for assessments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssessmentRepositoryAdapter,
  IdentificationRepositoryAdapter,
} from "@guardloop/adapters/assessments";
import { getIdGeneratorService } from "@guardloop/adapters";
import type { AdapterDynamoDBClient } from "@guardloop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateRiskAssessment,
  ExecuteCreateRiskIdentification,
  ExecuteGetRiskAssessment,
  ExecuteGetRiskIdentification,
  ExecuteListRiskAssessments,
  ExecuteListRiskIdentifications,
} from "@guardloop/services/assessments/usecases";
// Ports (interfaces)
import type {
  AssessmentRepository,
  IdentificationRepository,
} from "@guardloop/services/assessments/ports";

export interface AssessmentsDomainModule {
  repos: {
    assessments: AssessmentRepository;
    identifications: IdentificationRepository;
  };
  useCases: {
    assessments: {
      create: ExecuteCreateRiskAssessment;
      get: ExecuteGetRiskAssessment;
      list: ExecuteListRiskAssessments;
    };
    identifications: {
      create: ExecuteCreateRiskIdentification;
      get: ExecuteGetRiskIdentification;
      list: ExecuteListRiskIdentifications;
    };
  };
}

export function buildAssessmentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssessmentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assessments?: AssessmentRepository;
      identifications?: IdentificationRepository;
    } = {};

    obj.assessments = new AssessmentRepositoryAdapter(dynamoClient);
    obj.identifications = new IdentificationRepositoryAdapter(dynamoClient);
    return {
      assessments: obj.assessments!,
      identifications: obj.identifications!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assessments: {
      create: new ExecuteCreateRiskAssessment(executionContext, idGenerator, repos.assessments),
      get: new ExecuteGetRiskAssessment(executionContext, idGenerator, repos.assessments),
      list: new ExecuteListRiskAssessments(executionContext, idGenerator, repos.assessments),
    },
    identifications: {
      create: new ExecuteCreateRiskIdentification(executionContext, idGenerator, repos.identifications),
      get: new ExecuteGetRiskIdentification(executionContext, idGenerator, repos.identifications),
      list: new ExecuteListRiskIdentifications(executionContext, idGenerator, repos.identifications),
    },
  };
  return { repos, useCases: useCases as AssessmentsDomainModule["useCases"] };
}
