/**
 * AlertRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AlertRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AlertRepository,
} from "@guardloop/services/monitoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AlertRepositoryDdb } from "./alert-repository.ddb.js";

/**
 * AlertRepositoryAdapter
 *
 * Implements AlertRepository port for infrastructure layer.
 */
export class AlertRepositoryAdapter implements AlertRepository {
  private readonly ddb: AlertRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AlertRepositoryDdb(this.dynamoClient);
  }

  async listMonitorAlerts(input: Parameters<AlertRepository['listMonitorAlerts']>[0]): Promise<Awaited<ReturnType<AlertRepository['listMonitorAlerts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listMonitorAlerts(input);
  }

  async raiseMonitorAlert(input: Parameters<AlertRepository['raiseMonitorAlert']>[0]): Promise<Awaited<ReturnType<AlertRepository['raiseMonitorAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.raiseMonitorAlert(input);
  }

  async getMonitorAlert(input: Parameters<AlertRepository['getMonitorAlert']>[0]): Promise<Awaited<ReturnType<AlertRepository['getMonitorAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getMonitorAlert(input);
  }
}
