/**
 * AssessmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssessmentRepository Port
 *
 * DDD: Application port for assessmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRiskAssessmentInput, CreateRiskAssessmentOutput, GetRiskAssessmentInput, GetRiskAssessmentOutput, ListRiskAssessmentsInput, ListRiskAssessmentsOutput } from "../dto/assessment.dto";
export interface AssessmentRepository {
  listRiskAssessments(input: ListRiskAssessmentsInput): Promise<ListRiskAssessmentsOutput>;
  createRiskAssessment(input: CreateRiskAssessmentInput): Promise<CreateRiskAssessmentOutput>;
  getRiskAssessment(input: GetRiskAssessmentInput): Promise<GetRiskAssessmentOutput>;
}

export type { CreateRiskAssessmentInput, CreateRiskAssessmentOutput, GetRiskAssessmentInput, GetRiskAssessmentOutput, ListRiskAssessmentsInput, ListRiskAssessmentsOutput } from "../dto/assessment.dto";
