/**
 * IdentificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentificationRepository Port
 *
 * DDD: Application port for identificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRiskIdentificationInput, CreateRiskIdentificationOutput, GetRiskIdentificationInput, GetRiskIdentificationOutput, ListRiskIdentificationsInput, ListRiskIdentificationsOutput } from "../dto/identification.dto";
export interface IdentificationRepository {
  listRiskIdentifications(input: ListRiskIdentificationsInput): Promise<ListRiskIdentificationsOutput>;
  createRiskIdentification(input: CreateRiskIdentificationInput): Promise<CreateRiskIdentificationOutput>;
  getRiskIdentification(input: GetRiskIdentificationInput): Promise<GetRiskIdentificationOutput>;
}

export type { CreateRiskIdentificationInput, CreateRiskIdentificationOutput, GetRiskIdentificationInput, GetRiskIdentificationOutput, ListRiskIdentificationsInput, ListRiskIdentificationsOutput } from "../dto/identification.dto";
