/**
 * CreatePromotionGate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PromotionGateEvaluateRequest } from "@guardloop/core/controls";
import { controlsSchemas } from "@guardloop/core/controls";

export function createCreatePromotionGateRequest(overrides: Partial<PromotionGateEvaluateRequest> = {}) {
  const raw = {
    modelVersion: overrides.modelVersion ?? faker.lorem.word(),
    ...overrides,
  };

  return controlsSchemas.PromotionGateEvaluateRequest.parse(raw);
}
