/**
 * RemediationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RemediationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RemediationRepository,
} from "@guardloop/services/remediations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RemediationRepositoryDdb } from "./remediation-repository.ddb.js";

/**
 * RemediationRepositoryAdapter
 *
 * Implements RemediationRepository port for infrastructure layer.
 */
export class RemediationRepositoryAdapter implements RemediationRepository {
  private readonly ddb: RemediationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RemediationRepositoryDdb(this.dynamoClient);
  }

  async listRemediations(input: Parameters<RemediationRepository['listRemediations']>[0]): Promise<Awaited<ReturnType<RemediationRepository['listRemediations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRemediations(input);
  }

  async openRemediation(input: Parameters<RemediationRepository['openRemediation']>[0]): Promise<Awaited<ReturnType<RemediationRepository['openRemediation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openRemediation(input);
  }

  async getRemediation(input: Parameters<RemediationRepository['getRemediation']>[0]): Promise<Awaited<ReturnType<RemediationRepository['getRemediation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRemediation(input);
  }

  async updateRemediation(input: Parameters<RemediationRepository['updateRemediation']>[0]): Promise<Awaited<ReturnType<RemediationRepository['updateRemediation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateRemediation(input);
  }
}
