/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Controls Domain Use Cases
 * 
 * List of all use case names for the controls domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONTROLS_USE_CASES = [
  "executeCreateControlTest",
  "executeCreateSandboxEvidence",
  "executeEvaluatePromotionGate",
  "executeGetControlTest",
  "executeListControlTests",
  "executeListPromotionGates",
  "executeListSandboxEvidence"
] as const;
