/**
 * Policies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policies Domain Module - Composition root
 *
 * DDD: Composition root for policies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AppetiteRepositoryAdapter,
  FairnessRepositoryAdapter,
} from "@guardloop/adapters/policies";
import { getIdGeneratorService } from "@guardloop/adapters";
import type { AdapterDynamoDBClient } from "@guardloop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateFairnessPolicy,
  ExecuteCreateRiskAppetiteLimit,
  ExecuteGetFairnessPolicy,
  ExecuteGetRiskAppetiteLimit,
  ExecuteListFairnessPolicies,
  ExecuteListRiskAppetiteLimits,
  ExecutePublishFairnessPolicy,
} from "@guardloop/services/policies/usecases";
// Ports (interfaces)
import type {
  AppetiteRepository,
  FairnessRepository,
} from "@guardloop/services/policies/ports";

export interface PoliciesDomainModule {
  repos: {
    appetites: AppetiteRepository;
    fairnesses: FairnessRepository;
  };
  useCases: {
    appetites: {
      create: ExecuteCreateRiskAppetiteLimit;
      get: ExecuteGetRiskAppetiteLimit;
      list: ExecuteListRiskAppetiteLimits;
    };
    fairnesses: {
      create: ExecuteCreateFairnessPolicy;
      get: ExecuteGetFairnessPolicy;
      list: ExecuteListFairnessPolicies;
    };
  };
}

export function buildPoliciesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PoliciesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      appetites?: AppetiteRepository;
      fairnesses?: FairnessRepository;
    } = {};

    obj.appetites = new AppetiteRepositoryAdapter(dynamoClient);
    obj.fairnesses = new FairnessRepositoryAdapter(dynamoClient);
    return {
      appetites: obj.appetites!,
      fairnesses: obj.fairnesses!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    appetites: {
      create: new ExecuteCreateRiskAppetiteLimit(executionContext, idGenerator, repos.appetites),
      get: new ExecuteGetRiskAppetiteLimit(executionContext, idGenerator, repos.appetites),
      list: new ExecuteListRiskAppetiteLimits(executionContext, idGenerator, repos.appetites),
    },
    fairnesses: {
      create: new ExecuteCreateFairnessPolicy(executionContext, idGenerator, repos.fairnesses),
      get: new ExecuteGetFairnessPolicy(executionContext, idGenerator, repos.fairnesses),
      list: new ExecuteListFairnessPolicies(executionContext, idGenerator, repos.fairnesses),
    },
  };
  return { repos, useCases: useCases as PoliciesDomainModule["useCases"] };
}
