/**
 * Routes for Appetite
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRiskAppetiteLimit, getRiskAppetiteLimit, listRiskAppetiteLimits } from "../handlers/appetite.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { RiskAppetiteLimitCreateRequest } from "@guardloop/core/policies/types";

// Fastify types are available globally
export async function appetiteRoutes(fastify: FastifyInstance) {
  // POST /v1/policies/appetite (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policies/appetite",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: RiskAppetiteLimitCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await createRiskAppetiteLimit(request, reply, deps);
      });
    }
  );


  // GET /v1/policies/appetite (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies/appetite",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await listRiskAppetiteLimits(request, reply, deps);
      });
    }
  );


  // GET /v1/policies/appetite/{appetiteLimitId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies/appetite/:appetiteLimitId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { appetiteLimitId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await getRiskAppetiteLimit(request, reply, deps);
      });
    }
  );


}
