/**
 * Routes for Fairness
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createFairnessPolicy, getFairnessPolicy, listFairnessPolicies } from "../handlers/fairness.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { FairnessPolicyCreateRequest } from "@guardloop/core/policies/types";

// Fastify types are available globally
export async function fairnessRoutes(fastify: FastifyInstance) {
  // POST /v1/policies/fairness (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policies/fairness",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: FairnessPolicyCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await createFairnessPolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/policies/fairness (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies/fairness",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await listFairnessPolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/policies/fairness/{fairnessPolicyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies/fairness/:fairnessPolicyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { fairnessPolicyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await getFairnessPolicy(request, reply, deps);
      });
    }
  );


}
