/**
 * Handlers for Assessment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssessmentsDomainModule } from "../dependencies/assessments-ddd.dependencies.js";
import type { RiskAssessmentCreateRequest } from "@guardloop/core/assessments/types";
import type { CreateRiskAssessmentInput, GetRiskAssessmentInput, ListRiskAssessmentsInput } from "@guardloop/services/assessments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases/{useCaseId}/assessments
 * Operation: listRiskAssessments
 */
export async function listRiskAssessments(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRiskAssessmentsInput = {
    useCaseId: request.params.useCaseId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.assessments.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/use-cases/{useCaseId}/assessments
 * Operation: createRiskAssessment
 */
export async function createRiskAssessment(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: RiskAssessmentCreateRequest }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRiskAssessmentInput = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.assessments.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/use-cases/{useCaseId}/assessments/{assessmentId}
 * Operation: getRiskAssessment
 */
export async function getRiskAssessment(
  request: FastifyRequest<{ Params: { useCaseId: string, assessmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRiskAssessmentInput = {
    useCaseId: request.params.useCaseId,
    assessmentId: request.params.assessmentId,
  };
  const result = await deps.useCases.assessments.get.execute(input);
  return reply.code(200).send(result);
}


