/**
 * Handlers for Identification
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssessmentsDomainModule } from "../dependencies/assessments-ddd.dependencies.js";
import type { RiskIdentificationCreateRequest } from "@guardloop/core/assessments/types";
import type { CreateRiskIdentificationInput, GetRiskIdentificationInput, ListRiskIdentificationsInput } from "@guardloop/services/assessments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases/{useCaseId}/identifications
 * Operation: listRiskIdentifications
 */
export async function listRiskIdentifications(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRiskIdentificationsInput = {
    useCaseId: request.params.useCaseId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.identifications.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/use-cases/{useCaseId}/identifications
 * Operation: createRiskIdentification
 */
export async function createRiskIdentification(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: RiskIdentificationCreateRequest }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRiskIdentificationInput = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.identifications.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/use-cases/{useCaseId}/identifications/{identificationId}
 * Operation: getRiskIdentification
 */
export async function getRiskIdentification(
  request: FastifyRequest<{ Params: { useCaseId: string, identificationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRiskIdentificationInput = {
    useCaseId: request.params.useCaseId,
    identificationId: request.params.identificationId,
  };
  const result = await deps.useCases.identifications.get.execute(input);
  return reply.code(200).send(result);
}


