/**
 * Controls DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Controls Domain Module - Composition root
 *
 * DDD: Composition root for controls domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ControlTestRepositoryAdapter,
  PromotionGateRepositoryAdapter,
  SandboxEvidenceRepositoryAdapter,
} from "@guardloop/adapters/controls";
import { getIdGeneratorService } from "@guardloop/adapters";
import type { AdapterDynamoDBClient } from "@guardloop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateControlTest,
  ExecuteCreateSandboxEvidence,
  ExecuteGetControlTest,
  ExecuteListControlTests,
  ExecuteListPromotionGates,
  ExecuteListSandboxEvidence,
} from "@guardloop/services/controls/usecases";
// Ports (interfaces)
import type {
  ControlTestRepository,
  PromotionGateRepository,
  SandboxEvidenceRepository,
} from "@guardloop/services/controls/ports";

export interface ControlsDomainModule {
  repos: {
    controlTests: ControlTestRepository;
    promotionGates: PromotionGateRepository;
    sandboxEvidences: SandboxEvidenceRepository;
  };
  useCases: {
    controlTests: {
      create: ExecuteCreateControlTest;
      get: ExecuteGetControlTest;
      list: ExecuteListControlTests;
    };
    promotionGates: {
      list: ExecuteListPromotionGates;
    };
    sandboxEvidences: {
      create: ExecuteCreateSandboxEvidence;
      list: ExecuteListSandboxEvidence;
    };
  };
}

export function buildControlsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ControlsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      controlTests?: ControlTestRepository;
      promotionGates?: PromotionGateRepository;
      sandboxEvidences?: SandboxEvidenceRepository;
    } = {};

    obj.controlTests = new ControlTestRepositoryAdapter(dynamoClient);
    obj.promotionGates = new PromotionGateRepositoryAdapter(dynamoClient);
    obj.sandboxEvidences = new SandboxEvidenceRepositoryAdapter(dynamoClient);
    return {
      controlTests: obj.controlTests!,
      promotionGates: obj.promotionGates!,
      sandboxEvidences: obj.sandboxEvidences!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    controlTests: {
      create: new ExecuteCreateControlTest(executionContext, idGenerator, repos.controlTests),
      get: new ExecuteGetControlTest(executionContext, idGenerator, repos.controlTests),
      list: new ExecuteListControlTests(executionContext, idGenerator, repos.controlTests),
    },
    promotionGates: {
      list: new ExecuteListPromotionGates(executionContext, idGenerator, repos.promotionGates),
    },
    sandboxEvidences: {
      create: new ExecuteCreateSandboxEvidence(executionContext, idGenerator, repos.sandboxEvidences),
      list: new ExecuteListSandboxEvidence(executionContext, idGenerator, repos.sandboxEvidences),
    },
  };
  return { repos, useCases: useCases as ControlsDomainModule["useCases"] };
}
