/**
 * CreateIdentification DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RiskIdentificationCreateRequest } from "@guardloop/core/assessments";
import { assessmentsSchemas } from "@guardloop/core/assessments";

export function createCreateIdentificationRequest(overrides: Partial<RiskIdentificationCreateRequest> = {}) {
  const raw = {
    findings: overrides.findings ?? [],
    scope: overrides.scope ?? "use_case",
    triggers: overrides.triggers ?? [],
    ...overrides,
  };

  return assessmentsSchemas.RiskIdentificationCreateRequest.parse(raw);
}
