/**
 * ListIdentification DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRiskIdentificationsParams } from "@guardloop/core/assessments";

export function createListIdentificationRequest(overrides: Partial<ListRiskIdentificationsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
