/**
 * Routes for ControlTest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createControlTest, getControlTest, listControlTests } from "../handlers/control-test.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ControlTestCreateRequest } from "@guardloop/core/controls/types";

// Fastify types are available globally
export async function controlTestRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/control-tests (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/control-tests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: ControlTestCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await createControlTest(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/control-tests (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/control-tests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await listControlTests(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/control-tests/{controlTestId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/control-tests/:controlTestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string, controlTestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await getControlTest(request, reply, deps);
      });
    }
  );


}
