/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { promotionGateRoutes } from "./promotion-gate.routes.js";
export { sandboxEvidenceRoutes } from "./sandbox-evidence.routes.js";
export { controlTestRoutes } from "./control-test.routes.js";
