/**
 * Routes for PromotionGate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { evaluatePromotionGate, listPromotionGates } from "../handlers/promotion-gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { PromotionGateEvaluateRequest } from "@guardloop/core/controls/types";

// Fastify types are available globally
export async function promotionGateRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/promotion-gates (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/promotion-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: PromotionGateEvaluateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await evaluatePromotionGate(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/promotion-gates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/promotion-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await listPromotionGates(request, reply, deps);
      });
    }
  );


}
