/**
 * ExpandUseCaseToCustomer handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { expandUseCaseToCustomer } from "@guardloop/api-server/domains/use-cases/handlers";
import type { UseCasesDDDDependencies } from "@guardloop/api-server/domains/use-cases";
import { createCreateExpandToCustomerRequest } from "@guardloop/factories/use-cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { USECASES_USE_CASES } from "../__factories__/use-cases.js";

describe("ExpandUseCaseToCustomer", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: UseCasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<UseCasesDDDDependencies>(
      USECASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateExpandToCustomerRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeExpandUseCaseToCustomer, "execute").mockResolvedValue(useCaseResult);

    await expandUseCaseToCustomer(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeExpandUseCaseToCustomer.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
