/**
 * CreateExplanation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { ExplanationPackCreateRequest } from "@guardloop/core/explanations";
import { explanationsSchemas } from "@guardloop/core/explanations";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "exp";

export function createCreateExplanationRequest(overrides: Partial<ExplanationPackCreateRequest> = {}) {
  const raw = {
    decisionRef: overrides.decisionRef ?? faker.lorem.word(),
    fairnessPolicyVersion: overrides.fairnessPolicyVersion ?? faker.lorem.word(),
    featureRationaleSummary: overrides.featureRationaleSummary ?? faker.lorem.word(),
    piiMinimised: overrides.piiMinimised ?? faker.datatype.boolean(),
    useCaseId: overrides.useCaseId ?? `usc_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return explanationsSchemas.ExplanationPackCreateRequest.parse(raw);
}
