/**
 * Monitoring DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Monitoring Domain Module - Composition root
 *
 * DDD: Composition root for monitoring domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  AlertRepositoryAdapter,
} from "@guardloop/adapters/monitoring";
import { getIdGeneratorService } from "@guardloop/adapters";
import type { AdapterDynamoDBClient } from "@guardloop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeMonitorAlert,
  ExecuteGetMonitorAlert,
  ExecuteListMonitorAlerts,
  ExecuteRaiseMonitorAlert,
} from "@guardloop/services/monitoring/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  AlertRepository,
} from "@guardloop/services/monitoring/ports";

export interface MonitoringDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    alerts: AlertRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeMonitorAlert;
    };
    alerts: {
      get: ExecuteGetMonitorAlert;
      list: ExecuteListMonitorAlerts;
    };
  };
}

export function buildMonitoringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MonitoringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      alerts?: AlertRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.alerts = new AlertRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      alerts: obj.alerts!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeMonitorAlert(executionContext, idGenerator, repos.acknowledges),
    },
    alerts: {
      get: new ExecuteGetMonitorAlert(executionContext, idGenerator, repos.alerts),
      list: new ExecuteListMonitorAlerts(executionContext, idGenerator, repos.alerts),
    },
  };
  return { repos, useCases: useCases as MonitoringDomainModule["useCases"] };
}
