/**
 * Handlers for ControlTest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ControlsDomainModule } from "../dependencies/controls-ddd.dependencies.js";
import type { ControlTestCreateRequest } from "@guardloop/core/controls/types";
import type { CreateControlTestInput, GetControlTestInput, ListControlTestsInput } from "@guardloop/services/controls";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases/{useCaseId}/control-tests
 * Operation: listControlTests
 */
export async function listControlTests(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListControlTestsInput = {
    useCaseId: request.params.useCaseId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.controlTests.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/use-cases/{useCaseId}/control-tests
 * Operation: createControlTest
 */
export async function createControlTest(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: ControlTestCreateRequest }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateControlTestInput = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.controlTests.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/use-cases/{useCaseId}/control-tests/{controlTestId}
 * Operation: getControlTest
 */
export async function getControlTest(
  request: FastifyRequest<{ Params: { useCaseId: string, controlTestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetControlTestInput = {
    useCaseId: request.params.useCaseId,
    controlTestId: request.params.controlTestId,
  };
  const result = await deps.useCases.controlTests.get.execute(input);
  return reply.code(200).send(result);
}


