/**
 * Handlers for PromotionGate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ControlsDomainModule } from "../dependencies/controls-ddd.dependencies.js";
import type { PromotionGateEvaluateRequest } from "@guardloop/core/controls/types";
import type { EvaluatePromotionGateInput, ListPromotionGatesInput } from "@guardloop/services/controls";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases/{useCaseId}/promotion-gates
 * Operation: listPromotionGates
 */
export async function listPromotionGates(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPromotionGatesInput = {
    useCaseId: request.params.useCaseId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.promotionGates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/use-cases/{useCaseId}/promotion-gates
 * Operation: evaluatePromotionGate
 */
export async function evaluatePromotionGate(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: PromotionGateEvaluateRequest }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EvaluatePromotionGateInput = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.promotionGates.create.execute(input);
  return reply.code(200).send(result);
}


