/**
 * Appetite DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Appetite DTOs
 *
 * DDD: Application DTOs for Appetite use cases.
 */

import type { GetRiskAppetiteLimitParams, ListRiskAppetiteLimitsParams, RiskAppetiteLimitCreateRequest } from "@guardloop/core/policies/types";

export type ListRiskAppetiteLimitsInput = ListRiskAppetiteLimitsParams;

export type CreateRiskAppetiteLimitInput = RiskAppetiteLimitCreateRequest;

export type GetRiskAppetiteLimitInput = GetRiskAppetiteLimitParams;

export type ListRiskAppetiteLimitsOutput = {};

export type CreateRiskAppetiteLimitOutput = {};

export type GetRiskAppetiteLimitOutput = {};
