/**
 * Routes for Acknowledge
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { acknowledgeMonitorAlert } from "../handlers/acknowledge.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function acknowledgeRoutes(fastify: FastifyInstance) {
  // POST /v1/monitoring/alerts/{alertId}/acknowledge (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/monitoring/alerts/:alertId/acknowledge",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitoringDependenciesForRequest();
        await acknowledgeMonitorAlert(request, reply, deps);
      });
    }
  );


}
