/**
 * Routes for Alert
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getMonitorAlert, listMonitorAlerts, raiseMonitorAlert } from "../handlers/alert.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { MonitorAlertRaiseRequest } from "@guardloop/core/monitoring/types";

// Fastify types are available globally
export async function alertRoutes(fastify: FastifyInstance) {
  // GET /v1/monitoring/alerts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/monitoring/alerts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitoringDependenciesForRequest();
        await listMonitorAlerts(request, reply, deps);
      });
    }
  );


  // POST /v1/monitoring/alerts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/monitoring/alerts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: MonitorAlertRaiseRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitoringDependenciesForRequest();
        await raiseMonitorAlert(request, reply, deps);
      });
    }
  );


  // GET /v1/monitoring/alerts/{alertId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/monitoring/alerts/:alertId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitoringDependenciesForRequest();
        await getMonitorAlert(request, reply, deps);
      });
    }
  );


}
