/**
 * Routes for BindPolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { bindFairnessPolicy } from "../handlers/bind-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { BindFairnessPolicyRequest } from "@guardloop/core/use-cases/types";

// Fastify types are available globally
export async function bindPolicyRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/bind-policy (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/bind-policy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: BindFairnessPolicyRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await bindFairnessPolicy(request, reply, deps);
      });
    }
  );


}
