/**
 * Routes for UseCase
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAiUseCase, listAiUseCases, registerAiUseCase, updateAiUseCase } from "../handlers/use-case.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AiUseCaseCreateRequest, AiUseCaseUpdateRequest } from "@guardloop/core/use-cases/types";

// Fastify types are available globally
export async function useCaseRoutes(fastify: FastifyInstance) {
  // GET /v1/use-cases (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await listAiUseCases(request, reply, deps);
      });
    }
  );


  // POST /v1/use-cases (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AiUseCaseCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await registerAiUseCase(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await getAiUseCase(request, reply, deps);
      });
    }
  );


  // PATCH /v1/use-cases/{useCaseId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/use-cases/:useCaseId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AiUseCaseUpdateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await updateAiUseCase(request, reply, deps);
      });
    }
  );


}
