/**
 * CreateRiskAppetiteLimit handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createRiskAppetiteLimit } from "@guardloop/api-server/domains/policies/handlers";
import type { PoliciesDDDDependencies } from "@guardloop/api-server/domains/policies";
import { createCreateAppetiteRequest } from "@guardloop/factories/policies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { POLICIES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateRiskAppetiteLimit", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PoliciesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PoliciesDDDDependencies>(
      POLICIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateAppetiteRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateRiskAppetiteLimit, "execute").mockResolvedValue(useCaseResult);

    await createRiskAppetiteLimit(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateRiskAppetiteLimit.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
