/**
 * Routes for Assessment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRiskAssessment, getRiskAssessment, listRiskAssessments } from "../handlers/assessment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { RiskAssessmentCreateRequest } from "@guardloop/core/assessments/types";

// Fastify types are available globally
export async function assessmentRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/assessments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: RiskAssessmentCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await createRiskAssessment(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/assessments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await listRiskAssessments(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/assessments/{assessmentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/assessments/:assessmentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string, assessmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await getRiskAssessment(request, reply, deps);
      });
    }
  );


}
