/**
 * Routes for Identification
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRiskIdentification, getRiskIdentification, listRiskIdentifications } from "../handlers/identification.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { RiskIdentificationCreateRequest } from "@guardloop/core/assessments/types";

// Fastify types are available globally
export async function identificationRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/identifications (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/identifications",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: RiskIdentificationCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await createRiskIdentification(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/identifications (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/identifications",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await listRiskIdentifications(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/identifications/{identificationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/identifications/:identificationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string, identificationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await getRiskIdentification(request, reply, deps);
      });
    }
  );


}
