/**
 * CreateExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AuditExportCreateRequest } from "@guardloop/core/reporting";
import { reportingSchemas } from "@guardloop/core/reporting";

export function createCreateExportRequest(overrides: Partial<AuditExportCreateRequest> = {}) {
  const raw = {
    periodEnd: overrides.periodEnd ?? new Date().toISOString(),
    periodStart: overrides.periodStart ?? new Date().toISOString(),
    ...overrides,
  };

  return reportingSchemas.AuditExportCreateRequest.parse(raw);
}
