/**
 * GetExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAuditExportParams } from "@guardloop/core/reporting";

export function createGetExportRequest(overrides: Partial<GetAuditExportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
