/**
 * Assessment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assessment DTOs
 *
 * DDD: Application DTOs for Assessment use cases.
 */

import type { CreateRiskAssessmentParams, GetRiskAssessmentParams, ListRiskAssessmentsParams, RiskAssessmentCreateRequest } from "@guardloop/core/assessments/types";

export type ListRiskAssessmentsInput = ListRiskAssessmentsParams;

export type CreateRiskAssessmentInput = CreateRiskAssessmentParams & RiskAssessmentCreateRequest;

export type GetRiskAssessmentInput = GetRiskAssessmentParams;

export type ListRiskAssessmentsOutput = {};

export type CreateRiskAssessmentOutput = {};

export type GetRiskAssessmentOutput = {};
