/**
 * Identification DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Identification DTOs
 *
 * DDD: Application DTOs for Identification use cases.
 */

import type { CreateRiskIdentificationParams, GetRiskIdentificationParams, ListRiskIdentificationsParams, RiskIdentificationCreateRequest } from "@guardloop/core/assessments/types";

export type ListRiskIdentificationsInput = ListRiskIdentificationsParams;

export type CreateRiskIdentificationInput = CreateRiskIdentificationParams & RiskIdentificationCreateRequest;

export type GetRiskIdentificationInput = GetRiskIdentificationParams;

export type ListRiskIdentificationsOutput = {};

export type CreateRiskIdentificationOutput = {};

export type GetRiskIdentificationOutput = {};
