/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @guardloop/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@guardloop/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@guardloop/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@guardloop/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@guardloop/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@guardloop/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _assessments from "./assessments/index.js";
import * as _controls from "./controls/index.js";
import * as _explanations from "./explanations/index.js";
import * as _identity from "./identity/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _policies from "./policies/index.js";
import * as _remediations from "./remediations/index.js";
import * as _reporting from "./reporting/index.js";
import * as _useCases from "./use-cases/index.js";

// Export as namespaces
export const _shared = __shared;
export const assessments = _assessments;
export const controls = _controls;
export const explanations = _explanations;
export const identity = _identity;
export const monitoring = _monitoring;
export const policies = _policies;
export const remediations = _remediations;
export const reporting = _reporting;
export const useCases = _useCases;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@guardloop/core"; activity.types.*
//   - Direct exports: import * from "@guardloop/core/activity/types/index.js"
//   - Direct exports: import * from "@guardloop/core/activity/repositories/index.js"
//   - Direct exports: import * from "@guardloop/core/activity/models/index.js"
//   - Direct exports: import * from "@guardloop/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Assessments Service
export { schemas as AssessmentsSchemas } from "./assessments/schemas/assessments.schemas.js";

// Controls Service
export { schemas as ControlsSchemas } from "./controls/schemas/controls.schemas.js";

// Explanations Service
export { schemas as ExplanationsSchemas } from "./explanations/schemas/explanations.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Monitoring Service
export { schemas as MonitoringSchemas } from "./monitoring/schemas/monitoring.schemas.js";

// Policies Service
export { schemas as PoliciesSchemas } from "./policies/schemas/policies.schemas.js";

// Remediations Service
export { schemas as RemediationsSchemas } from "./remediations/schemas/remediations.schemas.js";

// Reporting Service
export { schemas as ReportingSchemas } from "./reporting/schemas/reporting.schemas.js";

// UseCases Service
export { schemas as UseCasesSchemas } from "./use-cases/schemas/use-cases.schemas.js";

