/**
 * BindPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BindPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BindPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BindPolicyRepository,
} from "@guardloop/services/use-cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BindPolicyRepositoryDdb } from "./bind-policy-repository.ddb.js";

/**
 * BindPolicyRepositoryAdapter
 *
 * Implements BindPolicyRepository port for infrastructure layer.
 */
export class BindPolicyRepositoryAdapter implements BindPolicyRepository {
  private readonly ddb: BindPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BindPolicyRepositoryDdb(this.dynamoClient);
  }

  async bindFairnessPolicy(input: Parameters<BindPolicyRepository['bindFairnessPolicy']>[0]): Promise<Awaited<ReturnType<BindPolicyRepository['bindFairnessPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.bindFairnessPolicy(input);
  }
}
