/**
 * UseCaseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseCaseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements UseCaseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  UseCaseRepository,
} from "@guardloop/services/use-cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { UseCaseRepositoryDdb } from "./use-case-repository.ddb.js";

/**
 * UseCaseRepositoryAdapter
 *
 * Implements UseCaseRepository port for infrastructure layer.
 */
export class UseCaseRepositoryAdapter implements UseCaseRepository {
  private readonly ddb: UseCaseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new UseCaseRepositoryDdb(this.dynamoClient);
  }

  async listAiUseCases(input: Parameters<UseCaseRepository['listAiUseCases']>[0]): Promise<Awaited<ReturnType<UseCaseRepository['listAiUseCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAiUseCases(input);
  }

  async registerAiUseCase(input: Parameters<UseCaseRepository['registerAiUseCase']>[0]): Promise<Awaited<ReturnType<UseCaseRepository['registerAiUseCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerAiUseCase(input);
  }

  async getAiUseCase(input: Parameters<UseCaseRepository['getAiUseCase']>[0]): Promise<Awaited<ReturnType<UseCaseRepository['getAiUseCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAiUseCase(input);
  }

  async updateAiUseCase(input: Parameters<UseCaseRepository['updateAiUseCase']>[0]): Promise<Awaited<ReturnType<UseCaseRepository['updateAiUseCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateAiUseCase(input);
  }
}
