/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Remediations Domain Use Cases
 * 
 * List of all use case names for the remediations domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const REMEDIATIONS_USE_CASES = [
  "executeGetRemediation",
  "executeListRemediations",
  "executeOpenRemediation",
  "executeUpdateRemediation"
] as const;
