/**
 * Export DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Export DTOs
 *
 * DDD: Application DTOs for Export use cases.
 */

import type { AuditExportCreateRequest, GetAuditExportParams, ListAuditExportsParams } from "@guardloop/core/reporting/types";

export type ListAuditExportsInput = ListAuditExportsParams;

export type CreateAuditExportInput = AuditExportCreateRequest;

export type GetAuditExportInput = GetAuditExportParams;

export type ListAuditExportsOutput = {};

export type CreateAuditExportOutput = {};

export type GetAuditExportOutput = {};
