/**
 * CreateAcknowledge DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AcknowledgeMonitorAlertParams } from "@guardloop/core/monitoring";

export function createCreateAcknowledgeRequest(overrides: Partial<AcknowledgeMonitorAlertParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
