/**
 * UseCase DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseCase DTOs
 *
 * DDD: Application DTOs for UseCase use cases.
 */

import type { AiUseCaseCreateRequest, AiUseCaseUpdateRequest, GetAiUseCaseParams, ListAiUseCasesParams, UpdateAiUseCaseParams } from "@guardloop/core/use-cases/types";

export type ListAiUseCasesInput = ListAiUseCasesParams;

export type RegisterAiUseCaseInput = AiUseCaseCreateRequest;

export type GetAiUseCaseInput = GetAiUseCaseParams;

export type UpdateAiUseCaseInput = UpdateAiUseCaseParams & AiUseCaseUpdateRequest;

export type ListAiUseCasesOutput = {};

export type RegisterAiUseCaseOutput = {};

export type GetAiUseCaseOutput = {};

export type UpdateAiUseCaseOutput = {};
