/**
 * AlertRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertRepository Port
 *
 * DDD: Application port for alertrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetMonitorAlertInput, GetMonitorAlertOutput, ListMonitorAlertsInput, ListMonitorAlertsOutput, RaiseMonitorAlertInput, RaiseMonitorAlertOutput } from "../dto/alert.dto";
export interface AlertRepository {
  listMonitorAlerts(input: ListMonitorAlertsInput): Promise<ListMonitorAlertsOutput>;
  raiseMonitorAlert(input: RaiseMonitorAlertInput): Promise<RaiseMonitorAlertOutput>;
  getMonitorAlert(input: GetMonitorAlertInput): Promise<GetMonitorAlertOutput>;
}

export type { GetMonitorAlertInput, GetMonitorAlertOutput, ListMonitorAlertsInput, ListMonitorAlertsOutput, RaiseMonitorAlertInput, RaiseMonitorAlertOutput } from "../dto/alert.dto";
