/**
 * GetExplanationPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getExplanationPack } from "@guardloop/api-server/domains/explanations/handlers";
import type { ExplanationsDDDDependencies } from "@guardloop/api-server/domains/explanations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { EXPLANATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetExplanationPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExplanationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExplanationsDDDDependencies>(
      EXPLANATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetExplanationPack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { explanationPackId: entity.id };

    await getExplanationPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetExplanationPack.execute).toHaveBeenCalledWith(expect.objectContaining({ explanationPackId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { explanationPackId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetExplanationPack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getExplanationPack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
