/**
 * Repository interface for ControlTest
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ControlTestEntity
} from "../models/control-test.entity.js";
import type {
  ListControlTestsParams,
  ControlTestCreateRequest
} from "../types/index.js";
/**
 * ControlTestRepository Interface
 */
export interface ControlTestRepository extends CreateReadRepository<ControlTestEntity, ControlTestCreateRequest, string, ListControlTestsParams> {

}
