/**
 * Repository interface for PromotionGate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PromotionGateEntity
} from "../models/promotion-gate.entity.js";
import type {
  ListPromotionGatesParams,
  PromotionGateEvaluateRequest
} from "../types/index.js";
/**
 * PromotionGateRepository Interface
 */
export interface PromotionGateRepository extends CreateReadRepository<PromotionGateEntity, PromotionGateEvaluateRequest, string, ListPromotionGatesParams> {

}
