/**
 * Repository interface for SandboxEvidence
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SandboxEvidenceEntity
} from "../models/sandbox-evidence.entity.js";
import type {
  ListSandboxEvidenceParams,
  SandboxEvidenceCreateRequest
} from "../types/index.js";
/**
 * SandboxEvidenceRepository Interface
 */
export interface SandboxEvidenceRepository extends CreateReadRepository<SandboxEvidenceEntity, SandboxEvidenceCreateRequest, string, ListSandboxEvidenceParams> {

}
