/**
 * PromotionGate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PromotionGateEntity } from "@guardloop/core/controls/models/index.js";
import { controlsSchemas } from "@guardloop/core/controls";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ctl";

export function createPromotionGate(overrides: Partial<PromotionGateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    decision: overrides.decision ?? "allow",
    fairnessTestsPassed: overrides.fairnessTestsPassed ?? faker.datatype.boolean(),
    modelVersion: overrides.modelVersion ?? faker.lorem.word(),
    promotionGateId: overrides.promotionGateId ?? `pgt_${ulid().toLowerCase()}`,
    useCaseId: overrides.useCaseId ?? `usc_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return controlsSchemas.PromotionGate.parse(raw);
}

export function promotionGateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPromotionGate(overrides));
}
