/**
 * FairnessRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessRepository Port
 *
 * DDD: Application port for fairnessrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateFairnessPolicyInput, CreateFairnessPolicyOutput, GetFairnessPolicyInput, GetFairnessPolicyOutput, ListFairnessPoliciesInput, ListFairnessPoliciesOutput } from "../dto/fairness.dto";
export interface FairnessRepository {
  listFairnessPolicies(input: ListFairnessPoliciesInput): Promise<ListFairnessPoliciesOutput>;
  createFairnessPolicy(input: CreateFairnessPolicyInput): Promise<CreateFairnessPolicyOutput>;
  getFairnessPolicy(input: GetFairnessPolicyInput): Promise<GetFairnessPolicyOutput>;
}

export type { CreateFairnessPolicyInput, CreateFairnessPolicyOutput, GetFairnessPolicyInput, GetFairnessPolicyOutput, ListFairnessPoliciesInput, ListFairnessPoliciesOutput } from "../dto/fairness.dto";
