/**
 * ControlTestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlTestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ControlTestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ControlTestRepository,
} from "@guardloop/services/controls";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ControlTestRepositoryDdb } from "./control-test-repository.ddb.js";

/**
 * ControlTestRepositoryAdapter
 *
 * Implements ControlTestRepository port for infrastructure layer.
 */
export class ControlTestRepositoryAdapter implements ControlTestRepository {
  private readonly ddb: ControlTestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ControlTestRepositoryDdb(this.dynamoClient);
  }

  async listControlTests(input: Parameters<ControlTestRepository['listControlTests']>[0]): Promise<Awaited<ReturnType<ControlTestRepository['listControlTests']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listControlTests(input);
  }

  async createControlTest(input: Parameters<ControlTestRepository['createControlTest']>[0]): Promise<Awaited<ReturnType<ControlTestRepository['createControlTest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createControlTest(input);
  }

  async getControlTest(input: Parameters<ControlTestRepository['getControlTest']>[0]): Promise<Awaited<ReturnType<ControlTestRepository['getControlTest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getControlTest(input);
  }
}
