/**
 * SandboxEvidenceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SandboxEvidenceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SandboxEvidenceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SandboxEvidenceRepository,
} from "@guardloop/services/controls";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SandboxEvidenceRepositoryDdb } from "./sandbox-evidence-repository.ddb.js";

/**
 * SandboxEvidenceRepositoryAdapter
 *
 * Implements SandboxEvidenceRepository port for infrastructure layer.
 */
export class SandboxEvidenceRepositoryAdapter implements SandboxEvidenceRepository {
  private readonly ddb: SandboxEvidenceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SandboxEvidenceRepositoryDdb(this.dynamoClient);
  }

  async listSandboxEvidence(input: Parameters<SandboxEvidenceRepository['listSandboxEvidence']>[0]): Promise<Awaited<ReturnType<SandboxEvidenceRepository['listSandboxEvidence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSandboxEvidence(input);
  }

  async createSandboxEvidence(input: Parameters<SandboxEvidenceRepository['createSandboxEvidence']>[0]): Promise<Awaited<ReturnType<SandboxEvidenceRepository['createSandboxEvidence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSandboxEvidence(input);
  }
}
