/**
 * ExecuteCreateSandboxEvidence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateSandboxEvidence Use Case
 *
 * DDD: Application use case for create SandboxEvidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateSandboxEvidenceInput, CreateSandboxEvidenceOutput } from "../dto/sandbox-evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { SandboxEvidenceRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateSandboxEvidence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sandboxEvidence: SandboxEvidenceRepository
  ) {}

  async execute(input: CreateSandboxEvidenceInput): Promise<CreateSandboxEvidenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: authorUserId, comments, lineOfDefence
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.lineOfDefence) {
      throw new ValidationError("lineOfDefence is required");
    }
    if (!input.comments) {
      throw new ValidationError("comments is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (controls domain)
    const entityId = this.idGenerator.ctlId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.sandboxEvidence.createSandboxEvidence({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateSandboxEvidenceOutput;
  }
}
