/**
 * ExecuteListPromotionGates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPromotionGates Use Case
 *
 * DDD: Application use case for list PromotionGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPromotionGatesInput, ListPromotionGatesOutput } from "../dto/promotion-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { PromotionGateRepository } from "../ports";

export class ExecuteListPromotionGates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly promotionGate: PromotionGateRepository
  ) {}

  async execute(input: ListPromotionGatesInput): Promise<ListPromotionGatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.promotionGate.listPromotionGates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPromotionGatesOutput;
  }
}
