/**
 * ExecuteListSandboxEvidence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSandboxEvidence Use Case
 *
 * DDD: Application use case for list SandboxEvidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSandboxEvidenceInput, ListSandboxEvidenceOutput } from "../dto/sandbox-evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { SandboxEvidenceRepository } from "../ports";

export class ExecuteListSandboxEvidence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sandboxEvidence: SandboxEvidenceRepository
  ) {}

  async execute(input: ListSandboxEvidenceInput): Promise<ListSandboxEvidenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.sandboxEvidence.listSandboxEvidence({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSandboxEvidenceOutput;
  }
}
