/**
 * FairnessRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FairnessRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FairnessRepository,
} from "@guardloop/services/policies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FairnessRepositoryDdb } from "./fairness-repository.ddb.js";

/**
 * FairnessRepositoryAdapter
 *
 * Implements FairnessRepository port for infrastructure layer.
 */
export class FairnessRepositoryAdapter implements FairnessRepository {
  private readonly ddb: FairnessRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FairnessRepositoryDdb(this.dynamoClient);
  }

  async listFairnessPolicies(input: Parameters<FairnessRepository['listFairnessPolicies']>[0]): Promise<Awaited<ReturnType<FairnessRepository['listFairnessPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFairnessPolicies(input);
  }

  async createFairnessPolicy(input: Parameters<FairnessRepository['createFairnessPolicy']>[0]): Promise<Awaited<ReturnType<FairnessRepository['createFairnessPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFairnessPolicy(input);
  }

  async getFairnessPolicy(input: Parameters<FairnessRepository['getFairnessPolicy']>[0]): Promise<Awaited<ReturnType<FairnessRepository['getFairnessPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFairnessPolicy(input);
  }
}
