/**
 * CreateRemediation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { RemediationCaseCreateRequest } from "@guardloop/core/remediations";
import { remediationsSchemas } from "@guardloop/core/remediations";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rmd";

export function createCreateRemediationRequest(overrides: Partial<RemediationCaseCreateRequest> = {}) {
  const raw = {
    owner: overrides.owner ?? faker.lorem.word(),
    useCaseId: overrides.useCaseId ?? `usc_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return remediationsSchemas.RemediationCaseCreateRequest.parse(raw);
}
