/**
 * UpdateRemediation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RemediationCaseUpdateRequest } from "@guardloop/core/remediations";
import { remediationsSchemas } from "@guardloop/core/remediations";

export function createUpdateRemediationRequest(overrides: Partial<RemediationCaseUpdateRequest> = {}) {
  const raw = {
    ...overrides,
  };

  return remediationsSchemas.RemediationCaseUpdateRequest.parse(raw);
}
