/**
 * ExecuteListMonitorAlerts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMonitorAlerts Use Case
 *
 * DDD: Application use case for list Alert.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMonitorAlertsInput, ListMonitorAlertsOutput } from "../dto/alert.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { AlertRepository } from "../ports";

export class ExecuteListMonitorAlerts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alert: AlertRepository
  ) {}

  async execute(input: ListMonitorAlertsInput): Promise<ListMonitorAlertsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.alert.listMonitorAlerts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMonitorAlertsOutput;
  }
}
