/**
 * IdentificationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentificationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IdentificationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IdentificationRepository,
} from "@guardloop/services/assessments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IdentificationRepositoryDdb } from "./identification-repository.ddb.js";

/**
 * IdentificationRepositoryAdapter
 *
 * Implements IdentificationRepository port for infrastructure layer.
 */
export class IdentificationRepositoryAdapter implements IdentificationRepository {
  private readonly ddb: IdentificationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IdentificationRepositoryDdb(this.dynamoClient);
  }

  async listRiskIdentifications(input: Parameters<IdentificationRepository['listRiskIdentifications']>[0]): Promise<Awaited<ReturnType<IdentificationRepository['listRiskIdentifications']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRiskIdentifications(input);
  }

  async createRiskIdentification(input: Parameters<IdentificationRepository['createRiskIdentification']>[0]): Promise<Awaited<ReturnType<IdentificationRepository['createRiskIdentification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createRiskIdentification(input);
  }

  async getRiskIdentification(input: Parameters<IdentificationRepository['getRiskIdentification']>[0]): Promise<Awaited<ReturnType<IdentificationRepository['getRiskIdentification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRiskIdentification(input);
  }
}
