/**
 * UpdateAiUseCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateAiUseCase } from "@guardloop/api-server/domains/use-cases/handlers";
import type { UseCasesDDDDependencies } from "@guardloop/api-server/domains/use-cases";
import { createUpdateUseCaseRequest } from "@guardloop/factories/use-cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { USECASES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateAiUseCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: UseCasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<UseCasesDDDDependencies>(
      USECASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateUseCaseRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { useCaseId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateAiUseCase, "execute").mockResolvedValue(useCaseResult);

    await updateAiUseCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateAiUseCase.execute).toHaveBeenCalledWith(expect.objectContaining({ useCaseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
