/**
 * CreateAlert DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { MonitorAlertRaiseRequest } from "@guardloop/core/monitoring";
import { monitoringSchemas } from "@guardloop/core/monitoring";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createCreateAlertRequest(overrides: Partial<MonitorAlertRaiseRequest> = {}) {
  const raw = {
    kind: overrides.kind ?? "drift",
    severity: overrides.severity ?? "low",
    useCaseId: overrides.useCaseId ?? `usc_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return monitoringSchemas.MonitorAlertRaiseRequest.parse(raw);
}
