/**
 * ListAlert DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListMonitorAlertsParams } from "@guardloop/core/monitoring";

export function createListAlertRequest(overrides: Partial<ListMonitorAlertsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
