/**
 * UseCases DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseCases Domain Module - Composition root
 *
 * DDD: Composition root for use-cases domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BindPolicyRepositoryAdapter,
  ExpandToCustomerRepositoryAdapter,
  UseCaseRepositoryAdapter,
} from "@guardloop/adapters/use-cases";
import { getIdGeneratorService } from "@guardloop/adapters";
import type { AdapterDynamoDBClient } from "@guardloop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteBindFairnessPolicy,
  ExecuteGetAiUseCase,
  ExecuteListAiUseCases,
  ExecuteRegisterAiUseCase,
  ExecuteUpdateAiUseCase,
} from "@guardloop/services/use-cases/usecases";
// Ports (interfaces)
import type {
  BindPolicyRepository,
  ExpandToCustomerRepository,
  UseCaseRepository,
} from "@guardloop/services/use-cases/ports";

export interface UseCasesDomainModule {
  repos: {
    bindPolicies: BindPolicyRepository;
    expandToCustomers: ExpandToCustomerRepository;
    useCases: UseCaseRepository;
  };
  useCases: {
    bindPolicies: {
      get: ExecuteBindFairnessPolicy;
    };
    useCases: {
      create: ExecuteRegisterAiUseCase;
      get: ExecuteGetAiUseCase;
      list: ExecuteListAiUseCases;
      update: ExecuteUpdateAiUseCase;
    };
  };
}

export function buildUseCasesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): UseCasesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      bindPolicies?: BindPolicyRepository;
      expandToCustomers?: ExpandToCustomerRepository;
      useCases?: UseCaseRepository;
    } = {};

    obj.bindPolicies = new BindPolicyRepositoryAdapter(dynamoClient);
    obj.expandToCustomers = new ExpandToCustomerRepositoryAdapter(dynamoClient);
    obj.useCases = new UseCaseRepositoryAdapter(dynamoClient);
    return {
      bindPolicies: obj.bindPolicies!,
      expandToCustomers: obj.expandToCustomers!,
      useCases: obj.useCases!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    bindPolicies: {
      get: new ExecuteBindFairnessPolicy(executionContext, idGenerator, repos.bindPolicies),
    },
    useCases: {
      create: new ExecuteRegisterAiUseCase(executionContext, idGenerator, repos.useCases),
      get: new ExecuteGetAiUseCase(executionContext, idGenerator, repos.useCases),
      list: new ExecuteListAiUseCases(executionContext, idGenerator, repos.useCases),
      update: new ExecuteUpdateAiUseCase(executionContext, idGenerator, repos.useCases),
    },
  };
  return { repos, useCases: useCases as UseCasesDomainModule["useCases"] };
}
