/**
 * GetRiskAssessment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRiskAssessment } from "@guardloop/api-server/domains/assessments/handlers";
import type { AssessmentsDDDDependencies } from "@guardloop/api-server/domains/assessments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { ASSESSMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRiskAssessment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssessmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssessmentsDDDDependencies>(
      ASSESSMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRiskAssessment, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { assessmentId: entity.id };

    await getRiskAssessment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRiskAssessment.execute).toHaveBeenCalledWith(expect.objectContaining({ assessmentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { assessmentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRiskAssessment, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRiskAssessment(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
