/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAssessmentsDomainModule } from "./assessments/dependencies/assessments-ddd.dependencies.js";
export { buildControlsDomainModule } from "./controls/dependencies/controls-ddd.dependencies.js";
export { buildExplanationsDomainModule } from "./explanations/dependencies/explanations-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildMonitoringDomainModule } from "./monitoring/dependencies/monitoring-ddd.dependencies.js";
export { buildPoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export { buildRemediationsDomainModule } from "./remediations/dependencies/remediations-ddd.dependencies.js";
export { buildReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export { buildUseCasesDomainModule } from "./use-cases/dependencies/use-cases-ddd.dependencies.js";

// Export all domain dependency types
export type { AssessmentsDomainModule } from "./assessments/dependencies/assessments-ddd.dependencies.js";
export type { ControlsDomainModule } from "./controls/dependencies/controls-ddd.dependencies.js";
export type { ExplanationsDomainModule } from "./explanations/dependencies/explanations-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { MonitoringDomainModule } from "./monitoring/dependencies/monitoring-ddd.dependencies.js";
export type { PoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export type { RemediationsDomainModule } from "./remediations/dependencies/remediations-ddd.dependencies.js";
export type { ReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export type { UseCasesDomainModule } from "./use-cases/dependencies/use-cases-ddd.dependencies.js";
