/**
 * OpenRemediation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { openRemediation } from "@guardloop/api-server/domains/remediations/handlers";
import type { RemediationsDDDDependencies } from "@guardloop/api-server/domains/remediations";
import { createCreateRemediationRequest } from "@guardloop/factories/remediations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { REMEDIATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("OpenRemediation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RemediationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RemediationsDDDDependencies>(
      REMEDIATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateRemediationRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeOpenRemediation, "execute").mockResolvedValue(useCaseResult);

    await openRemediation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeOpenRemediation.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
