/**
 * UpdateRemediation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateRemediation } from "@guardloop/api-server/domains/remediations/handlers";
import type { RemediationsDDDDependencies } from "@guardloop/api-server/domains/remediations";
import { createUpdateRemediationRequest } from "@guardloop/factories/remediations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { REMEDIATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateRemediation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RemediationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RemediationsDDDDependencies>(
      REMEDIATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateRemediationRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { remediationId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateRemediation, "execute").mockResolvedValue(useCaseResult);

    await updateRemediation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateRemediation.execute).toHaveBeenCalledWith(expect.objectContaining({ remediationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
