/**
 * ExplanationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExplanationRepository Port
 *
 * DDD: Application port for explanationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateExplanationPackInput, CreateExplanationPackOutput, GetExplanationPackInput, GetExplanationPackOutput, ListExplanationPacksInput, ListExplanationPacksOutput } from "../dto/explanation.dto";
export interface ExplanationRepository {
  listExplanationPacks(input: ListExplanationPacksInput): Promise<ListExplanationPacksOutput>;
  createExplanationPack(input: CreateExplanationPackInput): Promise<CreateExplanationPackOutput>;
  getExplanationPack(input: GetExplanationPackInput): Promise<GetExplanationPackOutput>;
}

export type { CreateExplanationPackInput, CreateExplanationPackOutput, GetExplanationPackInput, GetExplanationPackOutput, ListExplanationPacksInput, ListExplanationPacksOutput } from "../dto/explanation.dto";
