/**
 * ExecuteUpdateRemediation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateRemediation Use Case
 *
 * DDD: Application use case for update Remediation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateRemediationInput, UpdateRemediationOutput } from "../dto/remediation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { RemediationRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateRemediation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediation: RemediationRepository
  ) {}

  async execute(input: UpdateRemediationInput): Promise<UpdateRemediationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rmdId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).remediationId) {
      throw new ValidationError("remediationId is required");
    }
    const remediationId = (input as any).remediationId;

    // Load existing entity
    const existing = await this.remediation.openRemediation({ remediationId: remediationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${remediationId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.remediation.updateRemediation({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateRemediationOutput;
  }
}
