/**
 * ExecuteListRemediations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRemediations Use Case
 *
 * DDD: Application use case for list Remediation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRemediationsInput, ListRemediationsOutput } from "../dto/remediation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { RemediationRepository } from "../ports";

export class ExecuteListRemediations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediation: RemediationRepository
  ) {}

  async execute(input: ListRemediationsInput): Promise<ListRemediationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rmdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.remediation.listRemediations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRemediationsOutput;
  }
}
