/**
 * ControlTest Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ControlTestEntity } from "@guardloop/core/controls/models/index.js";
import { controlsSchemas } from "@guardloop/core/controls";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ctl";

export function createControlTest(overrides: Partial<ControlTestEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    cohortLabel: overrides.cohortLabel ?? faker.lorem.word(),
    controlTestId: overrides.controlTestId ?? `ctl_${ulid().toLowerCase()}`,
    fairnessPassed: overrides.fairnessPassed ?? faker.datatype.boolean(),
    policyVersion: overrides.policyVersion ?? faker.lorem.word(),
    useCaseId: overrides.useCaseId ?? `usc_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return controlsSchemas.ControlTest.parse(raw);
}

export function controlTestBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createControlTest(overrides));
}
