/**
 * BindPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BindPolicyRepository Port
 *
 * DDD: Application port for bindpolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { BindFairnessPolicyInput, BindFairnessPolicyOutput } from "../dto/bind-policy.dto";
export interface BindPolicyRepository {
  bindFairnessPolicy(input: BindFairnessPolicyInput): Promise<BindFairnessPolicyOutput>;
}

export type { BindFairnessPolicyInput, BindFairnessPolicyOutput } from "../dto/bind-policy.dto";
