/**
 * ExpandToCustomerRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExpandToCustomerRepository Port
 *
 * DDD: Application port for expandtocustomerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExpandUseCaseToCustomerInput, ExpandUseCaseToCustomerOutput } from "../dto/expand-to-customer.dto";
export interface ExpandToCustomerRepository {
  expandUseCaseToCustomer(input: ExpandUseCaseToCustomerInput): Promise<ExpandUseCaseToCustomerOutput>;
}

export type { ExpandUseCaseToCustomerInput, ExpandUseCaseToCustomerOutput } from "../dto/expand-to-customer.dto";
