/**
 * UseCaseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseCaseRepository Port
 *
 * DDD: Application port for usecaserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAiUseCaseInput, GetAiUseCaseOutput, ListAiUseCasesInput, ListAiUseCasesOutput, RegisterAiUseCaseInput, RegisterAiUseCaseOutput, UpdateAiUseCaseInput, UpdateAiUseCaseOutput } from "../dto/use-case.dto";
export interface UseCaseRepository {
  listAiUseCases(input: ListAiUseCasesInput): Promise<ListAiUseCasesOutput>;
  registerAiUseCase(input: RegisterAiUseCaseInput): Promise<RegisterAiUseCaseOutput>;
  getAiUseCase(input: GetAiUseCaseInput): Promise<GetAiUseCaseOutput>;
  updateAiUseCase(input: UpdateAiUseCaseInput): Promise<UpdateAiUseCaseOutput>;
}

export type { GetAiUseCaseInput, GetAiUseCaseOutput, ListAiUseCasesInput, ListAiUseCasesOutput, RegisterAiUseCaseInput, RegisterAiUseCaseOutput, UpdateAiUseCaseInput, UpdateAiUseCaseOutput } from "../dto/use-case.dto";
