/**
 * ExecuteCreateRiskIdentification - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateRiskIdentification Use Case
 *
 * DDD: Application use case for create Identification.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateRiskIdentificationInput, CreateRiskIdentificationOutput } from "../dto/identification.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { IdentificationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateRiskIdentification {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly identification: IdentificationRepository
  ) {}

  async execute(input: CreateRiskIdentificationInput): Promise<CreateRiskIdentificationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.asmId();

    // All field names extracted from OpenAPI spec: findings, owner, scope, triggers
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.findings) {
      throw new ValidationError("findings is required");
    }
    if (!input.triggers) {
      throw new ValidationError("triggers is required");
    }
    if (!input.scope) {
      throw new ValidationError("scope is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (assessments domain)
    const entityId = this.idGenerator.asmId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.identification.createRiskIdentification({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateRiskIdentificationOutput;
  }
}
