/**
 * ExecuteCreateRiskAppetiteLimit - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateRiskAppetiteLimit Use Case
 *
 * DDD: Application use case for create Appetite.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateRiskAppetiteLimitInput, CreateRiskAppetiteLimitOutput } from "../dto/appetite.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { AppetiteRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateRiskAppetiteLimit {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appetite: AppetiteRepository
  ) {}

  async execute(input: CreateRiskAppetiteLimitInput): Promise<CreateRiskAppetiteLimitOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: biasTolerance, explainabilityCoverage, notes, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }
    if (!input.biasTolerance) {
      throw new ValidationError("biasTolerance is required");
    }
    if (!input.explainabilityCoverage) {
      throw new ValidationError("explainabilityCoverage is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (policies domain)
    const entityId = this.idGenerator.polId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.appetite.createRiskAppetiteLimit({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateRiskAppetiteLimitOutput;
  }
}
