/**
 * ExecuteListFairnessPolicies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFairnessPolicies Use Case
 *
 * DDD: Application use case for list Fairness.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFairnessPoliciesInput, ListFairnessPoliciesOutput } from "../dto/fairness.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { FairnessRepository } from "../ports";

export class ExecuteListFairnessPolicies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fairness: FairnessRepository
  ) {}

  async execute(input: ListFairnessPoliciesInput): Promise<ListFairnessPoliciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.fairness.listFairnessPolicies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFairnessPoliciesOutput;
  }
}
