/**
 * ExecuteGetFairnessPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetFairnessPolicy Use Case
 *
 * DDD: Application use case for get Fairness.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetFairnessPolicyInput, GetFairnessPolicyOutput } from "../dto/fairness.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { FairnessRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetFairnessPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fairness: FairnessRepository
  ) {}

  async execute(input: GetFairnessPolicyInput): Promise<GetFairnessPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).fairnessPolicyId) {
      throw new ValidationError("fairnessPolicyId is required");
    }
    const fairnesspolicyId = (input as any).fairnessPolicyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.fairness.getFairnessPolicy({ fairnessPolicyId: fairnesspolicyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${fairnesspolicyId}`);
    }

    return entity as GetFairnessPolicyOutput;
  }
}
