/**
 * ExecuteGetRiskAppetiteLimit - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRiskAppetiteLimit Use Case
 *
 * DDD: Application use case for get Appetite.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRiskAppetiteLimitInput, GetRiskAppetiteLimitOutput } from "../dto/appetite.dto";
import type { ExecutionContextService, IdGeneratorService } from "@guardloop/services/_shared/index.js";
import type { AppetiteRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetRiskAppetiteLimit {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appetite: AppetiteRepository
  ) {}

  async execute(input: GetRiskAppetiteLimitInput): Promise<GetRiskAppetiteLimitOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).appetiteLimitId) {
      throw new ValidationError("appetiteLimitId is required");
    }
    const appetitelimitId = (input as any).appetiteLimitId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.appetite.getRiskAppetiteLimit({ appetiteLimitId: appetitelimitId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${appetitelimitId}`);
    }

    return entity as GetRiskAppetiteLimitOutput;
  }
}
