/**
 * Explanation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Explanation DTOs
 *
 * DDD: Application DTOs for Explanation use cases.
 */

import type { ExplanationPackCreateRequest, GetExplanationPackParams, ListExplanationPacksParams } from "@guardloop/core/explanations/types";

export type ListExplanationPacksInput = ListExplanationPacksParams;

export type CreateExplanationPackInput = ExplanationPackCreateRequest;

export type GetExplanationPackInput = GetExplanationPackParams;

export type ListExplanationPacksOutput = {};

export type CreateExplanationPackOutput = {};

export type GetExplanationPackOutput = {};
