/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@guardloop/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@guardloop/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@guardloop/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _assessments from "./assessments/index.js";
import * as _controls from "./controls/index.js";
import * as _explanations from "./explanations/index.js";
import * as _identity from "./identity/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _policies from "./policies/index.js";
import * as _remediations from "./remediations/index.js";
import * as _reporting from "./reporting/index.js";
import * as _useCases from "./use-cases/index.js";

// Export as namespaces
export const assessments = _assessments;
export const controls = _controls;
export const explanations = _explanations;
export const identity = _identity;
export const monitoring = _monitoring;
export const policies = _policies;
export const remediations = _remediations;
export const reporting = _reporting;
export const useCases = _useCases;
