/**
 * Acknowledge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Acknowledge DTOs
 *
 * DDD: Application DTOs for Acknowledge use cases.
 */

import type { AcknowledgeMonitorAlertParams } from "@guardloop/core/monitoring/types";

export type AcknowledgeMonitorAlertInput = AcknowledgeMonitorAlertParams;

export type AcknowledgeMonitorAlertOutput = {};
