/**
 * Alert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alert DTOs
 *
 * DDD: Application DTOs for Alert use cases.
 */

import type { GetMonitorAlertParams, ListMonitorAlertsParams, MonitorAlertRaiseRequest } from "@guardloop/core/monitoring/types";

export type ListMonitorAlertsInput = ListMonitorAlertsParams;

export type RaiseMonitorAlertInput = MonitorAlertRaiseRequest;

export type GetMonitorAlertInput = GetMonitorAlertParams;

export type ListMonitorAlertsOutput = {};

export type RaiseMonitorAlertOutput = {};

export type GetMonitorAlertOutput = {};
