/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the controls domain.
 * Use these factories in tests to create test data.
 */

export { createControlTest } from "./control-test/entity/control-test.entity.factory.js";
export { createCreateControlTestRequest } from "./control-test/dto/create-control-test.dto.factory.js";
export { createCreatePromotionGateRequest } from "./promotion-gate/dto/create-promotion-gate.dto.factory.js";
export { createCreateSandboxEvidenceRequest } from "./sandbox-evidence/dto/create-sandbox-evidence.dto.factory.js";
export { createPromotionGate } from "./promotion-gate/entity/promotion-gate.entity.factory.js";
export { createSandboxEvidence } from "./sandbox-evidence/entity/sandbox-evidence.entity.factory.js";
