/**
 * Remediations Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const openRemediation_Body = z
  .object({
    useCaseId: z.string().regex(/^usc_[0-9A-HJKMNP-TV-Z]{26}$/),
    owner: z.string().min(1),
    boardReportable: z.boolean().optional().default(false),
    alertId: z
      .string()
      .regex(/^alt_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    dueAt: z.string().datetime({ offset: true }).optional(),
    summary: z.string().optional(),
  })
  .passthrough();
const updateRemediation_Body = z
  .object({
    owner: z.string().min(1),
    status: z.enum(['open', 'in_progress', 'closed']),
    boardReportable: z.boolean(),
    dueAt: z.string().datetime({ offset: true }),
    summary: z.string(),
  })
  .partial()
  .passthrough();

export const schemas: any = {
  openRemediation_Body,
  updateRemediation_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/remediations',
    alias: 'listRemediations',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'useCaseId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^usc_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['open', 'in_progress', 'closed']).optional(),
      },
      {
        name: 'boardReportable',
        type: 'Query',
        schema: z.boolean().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  remediationId: z
                    .string()
                    .regex(/^rmd_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string().regex(/^usc_[0-9A-HJKMNP-TV-Z]{26}$/),
                  owner: z.string().min(1),
                  status: z.enum(['open', 'in_progress', 'closed']),
                  boardReportable: z.boolean(),
                  alertId: z
                    .string()
                    .regex(/^alt_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  dueAt: z.string().datetime({ offset: true }).optional(),
                  summary: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/remediations',
    alias: 'openRemediation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: openRemediation_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            remediationId: z.string().regex(/^rmd_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^usc_[0-9A-HJKMNP-TV-Z]{26}$/),
            owner: z.string().min(1),
            status: z.enum(['open', 'in_progress', 'closed']),
            boardReportable: z.boolean(),
            alertId: z
              .string()
              .regex(/^alt_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            dueAt: z.string().datetime({ offset: true }).optional(),
            summary: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/remediations/:remediationId',
    alias: 'getRemediation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'remediationId',
        type: 'Path',
        schema: z.string().regex(/^rmd_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            remediationId: z.string().regex(/^rmd_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^usc_[0-9A-HJKMNP-TV-Z]{26}$/),
            owner: z.string().min(1),
            status: z.enum(['open', 'in_progress', 'closed']),
            boardReportable: z.boolean(),
            alertId: z
              .string()
              .regex(/^alt_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            dueAt: z.string().datetime({ offset: true }).optional(),
            summary: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/remediations/:remediationId',
    alias: 'updateRemediation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateRemediation_Body,
      },
      {
        name: 'remediationId',
        type: 'Path',
        schema: z.string().regex(/^rmd_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            remediationId: z.string().regex(/^rmd_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^usc_[0-9A-HJKMNP-TV-Z]{26}$/),
            owner: z.string().min(1),
            status: z.enum(['open', 'in_progress', 'closed']),
            boardReportable: z.boolean(),
            alertId: z
              .string()
              .regex(/^alt_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            dueAt: z.string().datetime({ offset: true }).optional(),
            summary: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
