/**
 * ControlTest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlTest DTOs
 *
 * DDD: Application DTOs for ControlTest use cases.
 */

import type { ControlTestCreateRequest, CreateControlTestParams, GetControlTestParams, ListControlTestsParams } from "@guardloop/core/controls/types";

export type ListControlTestsInput = ListControlTestsParams;

export type CreateControlTestInput = CreateControlTestParams & ControlTestCreateRequest;

export type GetControlTestInput = GetControlTestParams;

export type ListControlTestsOutput = {};

export type CreateControlTestOutput = {};

export type GetControlTestOutput = {};
