/**
 * PromotionGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionGate DTOs
 *
 * DDD: Application DTOs for PromotionGate use cases.
 */

import type { EvaluatePromotionGateParams, ListPromotionGatesParams, PromotionGateEvaluateRequest } from "@guardloop/core/controls/types";

export type ListPromotionGatesInput = ListPromotionGatesParams;

export type EvaluatePromotionGateInput = EvaluatePromotionGateParams & PromotionGateEvaluateRequest;

export type ListPromotionGatesOutput = {};

export type EvaluatePromotionGateOutput = {};
