/**
 * SandboxEvidence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SandboxEvidence DTOs
 *
 * DDD: Application DTOs for SandboxEvidence use cases.
 */

import type { CreateSandboxEvidenceParams, ListSandboxEvidenceParams, SandboxEvidenceCreateRequest } from "@guardloop/core/controls/types";

export type ListSandboxEvidenceInput = ListSandboxEvidenceParams;

export type CreateSandboxEvidenceInput = CreateSandboxEvidenceParams & SandboxEvidenceCreateRequest;

export type ListSandboxEvidenceOutput = {};

export type CreateSandboxEvidenceOutput = {};
