/**
 * Handlers for Fairness
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PoliciesDomainModule } from "../dependencies/policies-ddd.dependencies.js";
import type { FairnessPolicyCreateRequest } from "@guardloop/core/policies/types";
import type { CreateFairnessPolicyInput, GetFairnessPolicyInput, ListFairnessPoliciesInput } from "@guardloop/services/policies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/policies/fairness
 * Operation: listFairnessPolicies
 */
export async function listFairnessPolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListFairnessPoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.fairnesses.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/policies/fairness
 * Operation: createFairnessPolicy
 */
export async function createFairnessPolicy(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: FairnessPolicyCreateRequest }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateFairnessPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.fairnesses.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/policies/fairness/{fairnessPolicyId}
 * Operation: getFairnessPolicy
 */
export async function getFairnessPolicy(
  request: FastifyRequest<{ Params: { fairnessPolicyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetFairnessPolicyInput = {
    fairnessPolicyId: request.params.fairnessPolicyId,
  };
  const result = await deps.useCases.fairnesses.get.execute(input);
  return reply.code(200).send(result);
}


