/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the assessments domain.
 * Use these factories in tests to create test data.
 */

export { createCreateAssessmentRequest } from "./assessment/dto/create-assessment.dto.factory.js";
export { createCreateIdentificationRequest } from "./identification/dto/create-identification.dto.factory.js";
