/**
 * GetControlTest DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetControlTestParams } from "@guardloop/core/controls";

export function createGetControlTestRequest(overrides: Partial<GetControlTestParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
