/**
 * CreateControlTest handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createControlTest } from "@guardloop/api-server/domains/controls/handlers";
import type { ControlsDDDDependencies } from "@guardloop/api-server/domains/controls";
import { createControlTest as createControlTestEntity } from "@guardloop/factories/controls";
import { createCreateControlTestRequest } from "@guardloop/factories/controls";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@guardloop/tests/shared";
import { CONTROLS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateControlTest", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ControlsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ControlsDDDDependencies>(
      CONTROLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateControlTestRequest();
    const entity = createControlTestEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateControlTest, "execute").mockResolvedValue(useCaseResult);

    await createControlTest(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateControlTest.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
