/**
 * RemediationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: remediations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationRepository Port
 *
 * DDD: Application port for remediationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRemediationInput, GetRemediationOutput, ListRemediationsInput, ListRemediationsOutput, OpenRemediationInput, OpenRemediationOutput, UpdateRemediationInput, UpdateRemediationOutput } from "../dto/remediation.dto";
export interface RemediationRepository {
  listRemediations(input: ListRemediationsInput): Promise<ListRemediationsOutput>;
  openRemediation(input: OpenRemediationInput): Promise<OpenRemediationOutput>;
  getRemediation(input: GetRemediationInput): Promise<GetRemediationOutput>;
  updateRemediation(input: UpdateRemediationInput): Promise<UpdateRemediationOutput>;
}

export type { GetRemediationInput, GetRemediationOutput, ListRemediationsInput, ListRemediationsOutput, OpenRemediationInput, OpenRemediationOutput, UpdateRemediationInput, UpdateRemediationOutput } from "../dto/remediation.dto";
