/**
 * ControlTestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlTestRepository Port
 *
 * DDD: Application port for controltestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateControlTestInput, CreateControlTestOutput, GetControlTestInput, GetControlTestOutput, ListControlTestsInput, ListControlTestsOutput } from "../dto/control-test.dto";
export interface ControlTestRepository {
  listControlTests(input: ListControlTestsInput): Promise<ListControlTestsOutput>;
  createControlTest(input: CreateControlTestInput): Promise<CreateControlTestOutput>;
  getControlTest(input: GetControlTestInput): Promise<GetControlTestOutput>;
}

export type { CreateControlTestInput, CreateControlTestOutput, GetControlTestInput, GetControlTestOutput, ListControlTestsInput, ListControlTestsOutput } from "../dto/control-test.dto";
