/**
 * CreateAppetite DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RiskAppetiteLimitCreateRequest } from "@guardloop/core/policies";
import { policiesSchemas } from "@guardloop/core/policies";

export function createCreateAppetiteRequest(overrides: Partial<RiskAppetiteLimitCreateRequest> = {}) {
  const raw = {
    biasTolerance: overrides.biasTolerance ?? faker.number.int(),
    explainabilityCoverage: overrides.explainabilityCoverage ?? faker.number.int(),
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return policiesSchemas.RiskAppetiteLimitCreateRequest.parse(raw);
}
