/**
 * GetAppetite DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRiskAppetiteLimitParams } from "@guardloop/core/policies";

export function createGetAppetiteRequest(overrides: Partial<GetRiskAppetiteLimitParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
