/**
 * SandboxEvidence Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/controls.openapi.types.js";
import { schemas } from "../schemas/controls.schemas.js";

/**
 * Entity: SandboxEvidenceEntity
 * Description: Represents the SandboxEvidence domain model.
 * Source: schemas.SandboxEvidence
 * Type: Domain Entity (API)
 */
export const SandboxEvidenceEntitySchema = schemas.SandboxEvidence;
export type SandboxEvidenceEntity = components["schemas"]["SandboxEvidence"];
